swagger: "2.0"
info:
  version: 1.0.0
  title: wayfarer
  description: WayFarer is a public bus transportation booking service.
basePath: /api/v1
tags:
  - name: Authentication
    description: User authentication endpoints

consumes:
  - application/json
produces:
  - application/json

definitions:
  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        example: no_stress

  UserRegisterBody:
    type: object
    title: register
    required:
      - email
      - password
      - first_name
      - last_name
    properties:
      email:
        type: string
        format: email
        example: user1@site.com
      password:
        type: string
        format: password
        example: password
      first_name:
        type: string
        example: fuser1
      last_name:
        type: string
        example: luser1

  UserLoginBody:
    type: object
    title: login
    properties:
      email:
        type: string
        format: email
        example: user1@site.com
      password:
        type: string
        format: password
        example: password

  ErrorAPIResponse:
    type: object
    properties:
      status:
        type: string
      error:
        type: string

  AuthAPIResponse:
    type: object
    properties:
      status:
        type: string
      data:
        type: object
        properties:
          token:
            type: string
          first_name:
            type: string
          last_name:
            type: string
          email:
            type: string
            format: email
paths:
  /auth/signup:
    post:
      tags:
        - Authentication
      description: Register a new user
      summary: User can sign up
      operationId: signupUser
      produces:
        - application/json
      parameters:
        - name: register_body
          in: body
          description: User create object
          required: true
          schema:
            $ref: "#/definitions/UserRegisterBody"
      responses:
        '201':
          description: User got created
          schema:
            $ref: "#/definitions/AuthAPIResponse"
        '500':
          description: An internal server error occurs
          schema:
            $ref: "#/definitions/ErrorAPIResponse"
        '409':
          description: Indentical user exists
          schema:
            $ref: "#/definitions/ErrorAPIResponse"

  /auth/signin:
    post:
      tags:
        - Authentication
      description: Log a user in
      summary: User can sign in
      operationId: signinUser
      produces:
        - application/json
      parameters:
        - name: login_body
          in: body
          description: The email/password
          required: true
          schema:
            $ref: "#/definitions/UserLoginBody"
      responses:
        '302':
          description: User got created
          schema:
            $ref: "#/definitions/AuthAPIResponse"
        '401':
          description: User is not authorized the access
          schema:
            $ref: "#/definitions/ErrorAPIResponse"
        '404':
          description: No user with the prided credentials exists
          schema:
            $ref: "#/definitions/ErrorAPIResponse"
